spring.application.name=shopcloud

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shopcloud
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Servidor
app.cors.allowed-origin=http://localhost:5173
server.port=8080