spring.application.name=shopcloud

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shopcloud
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080